# Setup
title: orenoログ
tagline: "A Jekyll theme"
description: 'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url: https://orenodinner.github.io
baseurl: /

# remote theme supported: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: poole/lanyon
paginate: 5
permalink: pretty

# About/contact
author:
  name: orenodinner
  url: https://twitter.com/oreno_dinner
  email:
# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
